# Site settings
title: Zabawaba IO
email: zabawaba99@gmail.com
description: >
  An elephant never forgets but I forget what the elephant remembered
baseurl: ""
url: "http://stevenberlanga.com"
twitter_username: zabawaba
github_username:  zabawaba99

# Conversion
markdown: kramdown
excerpt_separator: "\n\n"